maybe final tests
husainof/rest_api_testing pull request #1
Opened 2023-04-08 15:11 UTC by husainof

2023-04-08 22:16 UTC, AlyonaParshina requested changes

2023-04-08 22:16 UTC, AlyonaParshina commented on src/test/java/org/husainof/models/Pokemon.java
> +class Ability{
почему бы не вынести класс способностей в отдельный файл?

2023-04-08 22:16 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +    @Description("Проверка логики данных покемонов: вес rattata больше, чем у pidgeotto; у rattata есть способность 'run-away'.")
апи тесты лучше не объединять в один кейс. т.к. если вес rattata будет меньше, то ассерт, что способность у него есть, уже не выполнится

2023-04-08 22:16 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +                    .params("limit", limit)
этот лимит проще оставить статикой здесь, без использования конфига. при тестировании пагинации обычно проверяется 2-3 комбинации значений, хранить их в конфиге особой нужды нет.

2023-04-08 22:16 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/testing.xml
> +            <class name = "org.husainof.tests.ApiTest" />
рекомендация как и в ui проекте. попробуй добавить несколько файлов с тестами и посмотреть как распараллелятся все тесты

2023-04-08 23:09 UTC, husainof commented on src/test/java/org/husainof/tests/testing.xml
> +            <class name = "org.husainof.tests.ApiTest" />
тесты параллелятся по классам

2023-04-10 01:44 UTC, AlyonaParshina requested changes

2023-04-10 01:44 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +        Pokemon pidgeotto =  RestAssured.given(requestSpec)
результат этого запроса в итоге не учитывается. значит он лишний и его надо убрать

2023-04-10 01:44 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +                    .body("results.name", hasSize(limit))
а зачем здесь доп проверка лимита? у тебя же есть отдельный тест на это

2023-04-10 01:44 UTC, AlyonaParshina commented on src/main/resources/application.conf
> +limit = 10
в тестах проставил лимит статикой, значит можно убрать лимит отсюда

2023-04-10 01:44 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +        Integer limit10 = 10;
проще всего добавить дата провайдер для этого теста, т.к. весь код идентичен, меняется только значение одной переменной.

2023-04-10 04:59 UTC, husainof commented on src/test/java/org/husainof/tests/ApiTest.java
> +        Integer limit10 = 10;
честно сказать, впервые слышу про дата провайдер. Имеется в виду параметризация тестов?

2023-04-10 05:19 UTC, husainof commented on src/test/java/org/husainof/tests/ApiTest.java
> +        Integer limit10 = 10;
Добавил дата провайдер

2023-04-10 13:12 UTC, AlyonaParshina requested changes

2023-04-10 13:12 UTC, AlyonaParshina commented on src/test/java/org/husainof/tests/ApiTest.java
> +                    .params("limit", limit)
откуда берется значение limit?
ты удалил переменную, но не подставил здесь значение вместо нее. 
после любых корректировок необходимо запускать тесты и проверять, что все работает

2023-04-10 13:33 UTC, husainof commented on src/test/java/org/husainof/tests/ApiTest.java
> +                    .params("limit", limit)
на локально у меня все работает, просто чтоб не делать пуш только здесь изменил, а эту строчку не заметил

2023-04-10 13:37 UTC, AlyonaParshina approved these changes

2023-04-10 14:13 UTC, merged